#!/usr/bin/env bash
set -euo pipefail

# Fleet product pre-commit gate. The fleet product carries no vendored skills,
# so there is no setup/skills-sync step — just the fleet-only hook surface
# generated by nix/pre-commit.nix.
pre-commit run --all-files --show-diff-on-failure

echo "✅ Pre-commit gates passed"
