# ### fleet-reusable-ci
# #### source: fleet
name: ⚡ Reusable Fleet

on:
  workflow_call:

jobs:
  validate:
    name: Validate Fleet
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - name: Run fleet validation
        run: nix develop .#ci -c ./scripts/ci/fleet.sh
